apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: p2p-k8s-discovery
  namespace: p2p-ns
rules:
  - apiGroups: [""]
    resources: ["endpoints", "pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: p2p-serviceaccount
  namespace: p2p-ns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: p2p-k8s-discovery-binding
  namespace: p2p-ns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: p2p-k8s-discovery
subjects:
  - kind: ServiceAccount
    name: p2p-serviceaccount
    namespace: p2p-ns
